spring:
  application:
    name: boilerplate
  jackson:
    serialization:
      write-dates-as-timestamps: false

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus,loggers,threaddump,conditions
  endpoint:
    health:
      show-details: when_authorized

micrometer:
  metrics:
    export:
      prometheus:
        enabled: true

logging:
  level:
    root: INFO

# Flyway migration defaults
spring:
  flyway:
    enabled: true
    locations: classpath:db/migration
    baseline-on-migrate: true

