package com.example.boilerplate.file;

import java.io.InputStream;
import java.util.Optional;
import org.springframework.core.io.Resource;

/**
 * Where uploaded bytes live. Keys are generated by {@link FileService}, never taken from the
 * client. {@link LocalFileStorage} is the only implementation; an object-store one (S3 etc.) can
 * replace it without changing callers.
 */
public interface FileStorage {
  void store(String key, InputStream content);

  Optional<Resource> load(String key);

  /** Removes the bytes if present; failures are logged, not thrown. */
  void delete(String key);
}
